// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNFoylqtnb-YQtiMzS0legNPp-21-_trc',
    appId: '1:900579082268:web:1b225ce8d77c0b4ad25fd9',
    messagingSenderId: '900579082268',
    projectId: 'spacecraft-ec37f',
    authDomain: 'spacecraft-ec37f.firebaseapp.com',
    storageBucket: 'spacecraft-ec37f.firebasestorage.app',
    measurementId: 'G-F6TE8XEB2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQXhi9YhZLf8GgaOiLmiQeLHspnuQqx4',
    appId: '1:900579082268:android:0829cb1d0a27e1c0d25fd9',
    messagingSenderId: '900579082268',
    projectId: 'spacecraft-ec37f',
    storageBucket: 'spacecraft-ec37f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG-au2YflrNNvTpV04aa-_El1S9pvlo0Y',
    appId: '1:900579082268:ios:49e41da332ebcb87d25fd9',
    messagingSenderId: '900579082268',
    projectId: 'spacecraft-ec37f',
    storageBucket: 'spacecraft-ec37f.firebasestorage.app',
    iosBundleId: 'com.example.spacecraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG-au2YflrNNvTpV04aa-_El1S9pvlo0Y',
    appId: '1:900579082268:ios:49e41da332ebcb87d25fd9',
    messagingSenderId: '900579082268',
    projectId: 'spacecraft-ec37f',
    storageBucket: 'spacecraft-ec37f.firebasestorage.app',
    iosBundleId: 'com.example.spacecraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNFoylqtnb-YQtiMzS0legNPp-21-_trc',
    appId: '1:900579082268:web:955bde01db0c1525d25fd9',
    messagingSenderId: '900579082268',
    projectId: 'spacecraft-ec37f',
    authDomain: 'spacecraft-ec37f.firebaseapp.com',
    storageBucket: 'spacecraft-ec37f.firebasestorage.app',
    measurementId: 'G-HM4J6MSZVV',
  );
}
